######################################################################
# Automatically generated by qmake (2.01a) Sun Nov 11 16:39:00 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
LIBS += -lboost_date_time -lboost_thread

# Input
HEADERS += ScoreForm.h
FORMS += ScoreForm.ui
SOURCES += main.cpp ScoreForm.cpp Stoppable.cpp StdinGrabber.cpp
