#############################################################################
# Makefile for building: beer-die-sb
# Generated by qmake (2.01a) (Qt 4.8.2) on: Sun Nov 11 17:19:10 2012
# Project:  beer-die-sb.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile beer-die-sb.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -march=i486 -mtune=i686 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -march=i486 -mtune=i686 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/lib/qt/mkspecs/linux-g++ -I. -I/usr/lib/qt/include/QtCore -I/usr/lib/qt/include/QtGui -I/usr/lib/qt/include -I. -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/usr/lib/qt/lib
LIBS          = $(SUBLIBS)  -L/usr/lib/qt/lib -lboost_date_time -lboost_thread -lQtGui -L/usr/lib/qt/lib -L/usr/X11R6/lib -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		ScoreForm.cpp \
		Stoppable.cpp \
		StdinGrabber.cpp moc_ScoreForm.cpp
OBJECTS       = main.o \
		ScoreForm.o \
		Stoppable.o \
		StdinGrabber.o \
		moc_ScoreForm.o
DIST          = /usr/lib/qt/mkspecs/common/unix.conf \
		/usr/lib/qt/mkspecs/common/linux.conf \
		/usr/lib/qt/mkspecs/common/gcc-base.conf \
		/usr/lib/qt/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/qt/mkspecs/common/g++-base.conf \
		/usr/lib/qt/mkspecs/common/g++-unix.conf \
		/usr/lib/qt/mkspecs/qconfig.pri \
		/usr/lib/qt/mkspecs/modules/qt_phonon.pri \
		/usr/lib/qt/mkspecs/modules/qt_webkit_version.pri \
		/usr/lib/qt/mkspecs/features/qt_functions.prf \
		/usr/lib/qt/mkspecs/features/qt_config.prf \
		/usr/lib/qt/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt/mkspecs/features/default_pre.prf \
		/usr/lib/qt/mkspecs/features/release.prf \
		/usr/lib/qt/mkspecs/features/default_post.prf \
		/usr/lib/qt/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/lib/qt/mkspecs/features/warn_on.prf \
		/usr/lib/qt/mkspecs/features/qt.prf \
		/usr/lib/qt/mkspecs/features/unix/thread.prf \
		/usr/lib/qt/mkspecs/features/moc.prf \
		/usr/lib/qt/mkspecs/features/resources.prf \
		/usr/lib/qt/mkspecs/features/uic.prf \
		/usr/lib/qt/mkspecs/features/yacc.prf \
		/usr/lib/qt/mkspecs/features/lex.prf \
		/usr/lib/qt/mkspecs/features/include_source_dir.prf \
		beer-die-sb.pro
QMAKE_TARGET  = beer-die-sb
DESTDIR       = 
TARGET        = beer-die-sb

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_ScoreForm.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: beer-die-sb.pro  /usr/lib/qt/mkspecs/linux-g++/qmake.conf /usr/lib/qt/mkspecs/common/unix.conf \
		/usr/lib/qt/mkspecs/common/linux.conf \
		/usr/lib/qt/mkspecs/common/gcc-base.conf \
		/usr/lib/qt/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/qt/mkspecs/common/g++-base.conf \
		/usr/lib/qt/mkspecs/common/g++-unix.conf \
		/usr/lib/qt/mkspecs/qconfig.pri \
		/usr/lib/qt/mkspecs/modules/qt_phonon.pri \
		/usr/lib/qt/mkspecs/modules/qt_webkit_version.pri \
		/usr/lib/qt/mkspecs/features/qt_functions.prf \
		/usr/lib/qt/mkspecs/features/qt_config.prf \
		/usr/lib/qt/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt/mkspecs/features/default_pre.prf \
		/usr/lib/qt/mkspecs/features/release.prf \
		/usr/lib/qt/mkspecs/features/default_post.prf \
		/usr/lib/qt/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/lib/qt/mkspecs/features/warn_on.prf \
		/usr/lib/qt/mkspecs/features/qt.prf \
		/usr/lib/qt/mkspecs/features/unix/thread.prf \
		/usr/lib/qt/mkspecs/features/moc.prf \
		/usr/lib/qt/mkspecs/features/resources.prf \
		/usr/lib/qt/mkspecs/features/uic.prf \
		/usr/lib/qt/mkspecs/features/yacc.prf \
		/usr/lib/qt/mkspecs/features/lex.prf \
		/usr/lib/qt/mkspecs/features/include_source_dir.prf \
		/usr/lib/qt/lib/libQtGui.prl \
		/usr/lib/qt/lib/libQtCore.prl
	$(QMAKE) -o Makefile beer-die-sb.pro
/usr/lib/qt/mkspecs/common/unix.conf:
/usr/lib/qt/mkspecs/common/linux.conf:
/usr/lib/qt/mkspecs/common/gcc-base.conf:
/usr/lib/qt/mkspecs/common/gcc-base-unix.conf:
/usr/lib/qt/mkspecs/common/g++-base.conf:
/usr/lib/qt/mkspecs/common/g++-unix.conf:
/usr/lib/qt/mkspecs/qconfig.pri:
/usr/lib/qt/mkspecs/modules/qt_phonon.pri:
/usr/lib/qt/mkspecs/modules/qt_webkit_version.pri:
/usr/lib/qt/mkspecs/features/qt_functions.prf:
/usr/lib/qt/mkspecs/features/qt_config.prf:
/usr/lib/qt/mkspecs/features/exclusive_builds.prf:
/usr/lib/qt/mkspecs/features/default_pre.prf:
/usr/lib/qt/mkspecs/features/release.prf:
/usr/lib/qt/mkspecs/features/default_post.prf:
/usr/lib/qt/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/lib/qt/mkspecs/features/warn_on.prf:
/usr/lib/qt/mkspecs/features/qt.prf:
/usr/lib/qt/mkspecs/features/unix/thread.prf:
/usr/lib/qt/mkspecs/features/moc.prf:
/usr/lib/qt/mkspecs/features/resources.prf:
/usr/lib/qt/mkspecs/features/uic.prf:
/usr/lib/qt/mkspecs/features/yacc.prf:
/usr/lib/qt/mkspecs/features/lex.prf:
/usr/lib/qt/mkspecs/features/include_source_dir.prf:
/usr/lib/qt/lib/libQtGui.prl:
/usr/lib/qt/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile beer-die-sb.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/beer-die-sb1.0.0 || $(MKDIR) .tmp/beer-die-sb1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/beer-die-sb1.0.0/ && $(COPY_FILE) --parents ScoreForm.h .tmp/beer-die-sb1.0.0/ && $(COPY_FILE) --parents main.cpp ScoreForm.cpp Stoppable.cpp StdinGrabber.cpp .tmp/beer-die-sb1.0.0/ && $(COPY_FILE) --parents ScoreForm.ui .tmp/beer-die-sb1.0.0/ && (cd `dirname .tmp/beer-die-sb1.0.0` && $(TAR) beer-die-sb1.0.0.tar beer-die-sb1.0.0 && $(COMPRESS) beer-die-sb1.0.0.tar) && $(MOVE) `dirname .tmp/beer-die-sb1.0.0`/beer-die-sb1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/beer-die-sb1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_ScoreForm.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_ScoreForm.cpp
moc_ScoreForm.cpp: ui_ScoreForm.h \
		ScoreForm.h
	/usr/lib/qt/bin/moc $(DEFINES) $(INCPATH) ScoreForm.h -o moc_ScoreForm.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_ScoreForm.h
compiler_uic_clean:
	-$(DEL_FILE) ui_ScoreForm.h
ui_ScoreForm.h: ScoreForm.ui
	/usr/lib/qt/bin/uic ScoreForm.ui -o ui_ScoreForm.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp ScoreForm.h \
		ui_ScoreForm.h \
		StdinGrabber.h \
		Stoppable.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

ScoreForm.o: ScoreForm.cpp ScoreForm.h \
		ui_ScoreForm.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ScoreForm.o ScoreForm.cpp

Stoppable.o: Stoppable.cpp Stoppable.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Stoppable.o Stoppable.cpp

StdinGrabber.o: StdinGrabber.cpp StdinGrabber.h \
		Stoppable.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o StdinGrabber.o StdinGrabber.cpp

moc_ScoreForm.o: moc_ScoreForm.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ScoreForm.o moc_ScoreForm.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

